services:
  postgres:
    image: postgres:13
    restart: always
    ports:
      - "5342:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: LocalUser
      POSTGRES_PASSWORD: 12345
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 3s
      retries: 5

  mpss:
    image: gitlab/mpss/mpss:latest
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
    environment:
      # ASPNETCORE_ENVIRONMENT: "Development"
      Postgres__ConnectionString: "Host=localhost;Port=5432;Database=postgres;Username=LocalUser;Password=12345"
    healthcheck:
      test: curl --fail --insecure http://localhost:80/health || exit 1
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  pgdata:
    external: true
