DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'mpss') THEN
CREATE SCHEMA mpss;
END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS mpss."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
    );

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'mpss') THEN
CREATE SCHEMA mpss;
END IF;
END $EF$;

CREATE TABLE mpss."Counteragents" (
                                      "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                                      "Name" character varying(100) NOT NULL,
                                      "Contact" character varying(100) NOT NULL,
                                      "Phone" character varying(15) NOT NULL,
                                      "INN" bigint,
                                      "OGRN" bigint,
                                      "AccountNumber" numeric(20,0),
                                      "BIK" bigint,
                                      CONSTRAINT "PK_Counteragents" PRIMARY KEY ("Id")
);

CREATE TABLE mpss."Employees" (
                                  "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                                  "Name" character varying(100) NOT NULL,
                                  "Phone" character varying(20) NOT NULL,
                                  "IsDriver" boolean NOT NULL,
                                  "Passport" numeric(20,0),
                                  "DateOfBirth" timestamp with time zone NOT NULL,
                                  "INN" numeric(20,0),
                                  "AccountNumber" numeric(20,0),
                                  "BIK" numeric(20,0),
                                  CONSTRAINT "PK_Employees" PRIMARY KEY ("Id")
);

CREATE TABLE mpss."EmployeeShifts" (
                                       "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                                       "ProjectId" integer NOT NULL,
                                       "EmployeeId" integer NOT NULL,
                                       "Date" timestamp with time zone NOT NULL,
                                       "Arrival" timestamp with time zone,
                                       "Departure" timestamp with time zone,
                                       "HoursWorked" float,
                                       "TravelTime" float,
                                       "ConsiderTravel" boolean NOT NULL,
                                       "ISN" integer NOT NULL,
                                       CONSTRAINT "PK_EmployeeShifts" PRIMARY KEY ("Id")
);

CREATE TABLE mpss."Expenses" (
                                 "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                                 "ProjectId" integer NOT NULL,
                                 "Name" text NOT NULL,
                                 "Amount" numeric(18,2),
                                 "Description" character varying(500),
                                 "Type" integer NOT NULL,
                                 "IsPaidByCompany" boolean NOT NULL,
                                 CONSTRAINT "PK_Expenses" PRIMARY KEY ("Id")
);

CREATE TABLE mpss."ProductComponents" (
                                          "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                                          "ProductId" integer NOT NULL,
                                          "Name" character varying(100) NOT NULL,
                                          "Quantity" integer,
                                          "Weight" real,
                                          CONSTRAINT "PK_ProductComponents" PRIMARY KEY ("Id")
);

CREATE TABLE mpss."Products" (
                                 "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                                 "Name" character varying(100) NOT NULL,
                                 "Cost" numeric(18,2) NOT NULL,
                                 CONSTRAINT "PK_Products" PRIMARY KEY ("Id")
);

CREATE TABLE mpss."ProjectProducts" (
                                        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                                        "ProjectId" integer NOT NULL,
                                        "ProductId" integer NOT NULL,
                                        "Quantity" integer NOT NULL,
                                        "Markup" numeric(18,2) NOT NULL,
                                        CONSTRAINT "PK_ProjectProducts" PRIMARY KEY ("Id")
);

CREATE TABLE mpss."Projects" (
                                 "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                                 "Name" text NOT NULL,
                                 "Address" text NOT NULL,
                                 "DeadlineDate" timestamp with time zone NOT NULL,
                                 "StartDate" timestamp with time zone NOT NULL,
                                 "DateSuspended" timestamp with time zone,
                                 "CounteragentId" integer,
                                 "ResponsibleEmployeeId" integer NOT NULL,
                                 "ManagerShare" real NOT NULL,
                                 "ProjectStatus" text NOT NULL,
                                 CONSTRAINT "PK_Projects" PRIMARY KEY ("Id"),
                                 CONSTRAINT "FK_Projects_Counteragents_CounteragentId" FOREIGN KEY ("CounteragentId") REFERENCES mpss."Counteragents" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_Projects_CounteragentId" ON mpss."Projects" ("CounteragentId");

INSERT INTO mpss."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240820130311_Initial', '8.0.7');

COMMIT;